<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-O81FVFFS" name="com.adda.main.MainClass" tests="6" failures="1" timestamp="12 Feb 2019 09:19:25 GMT" time="366.219" errors="0">
  <testcase name="createConversations" time="60.540" classname="com.adda.main.MainClass"/>
  <testcase name="AdminCreateNotice" time="50.654" classname="com.adda.main.MainClass"/>
  <testcase name="UserVerifyNotice" time="18.114" classname="com.adda.main.MainClass"/>
  <testcase name="verifyMyUnit" time="108.808" classname="com.adda.main.MainClass">
    <failure type="java.lang.AssertionError" message="Convinince charge of Debit Card when Amount payble is less than 2000 Checked expected [0.2] but found [110.0]">
      <![CDATA[java.lang.AssertionError: Convinince charge of Debit Card when Amount payble is less than 2000 Checked expected [0.2] but found [110.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at com.adda.home.MyUnit.makePayment(MyUnit.java:283)
	at com.adda.main.MainClass.verifyMyUnit(MainClass.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- verifyMyUnit -->
  <testcase name="validateDirectMessage" time="53.411" classname="com.adda.main.MainClass"/>
  <testcase name="ValidateHelpdesk" time="74.692" classname="com.adda.main.MainClass"/>
</testsuite> <!-- com.adda.main.MainClass -->
